/*----- PROTECTED REGION ID(Serial2ClientClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        Serial2ClientClass.h
//
// description : Include for the Serial2Client root class.
//               This class is the singleton class for
//                the Serial2Client device class.
//               It contains all properties and methods which the 
//               Serial2Client requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: alessio $
//
// $Revision: 1.2 $
// $Date: 2017-12-21 15:35:39 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Serial2ClientClass_H
#define Serial2ClientClass_H

#include <tango.h>
#include <Serial2Client.h>


/*----- PROTECTED REGION END -----*/	//	Serial2ClientClass.h


namespace Serial2Client_ns
{
/*----- PROTECTED REGION ID(Serial2ClientClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	Serial2ClientClass::classes for dynamic creation

/**
 *	The Serial2ClientClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  Serial2ClientClass : public Tango::DeviceClass
#else
class Serial2ClientClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(Serial2ClientClass::Additional DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Serial2ClientClass::Additional DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
		//	Method prototypes
		static Serial2ClientClass *init(const char *);
		static Serial2ClientClass *instance();
		~Serial2ClientClass();
		Tango::DbDatum	get_class_property(std::string &);
		Tango::DbDatum	get_default_device_property(std::string &);
		Tango::DbDatum	get_default_class_property(std::string &);

	protected:
		Serial2ClientClass(std::string &);
		static Serial2ClientClass *_instance;
		void command_factory();
		void attribute_factory(std::vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		std::string get_cvstag();
		std::string get_cvsroot();

	private:
		void device_factory(TANGO_UNUSED(const Tango::DevVarStringArray *));
		void create_static_attribute_list(std::vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,std::vector<Tango::Attr *> &);
		std::vector<std::string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname);
};

}	//	End of namespace

#endif   //	Serial2Client_H
