/*----- PROTECTED REGION ID(Serial2ClientStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        Serial2ClientStateMachine.cpp
//
// description : State machine file for the Serial2Client class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: alessio $
//
// $Revision: 1.2 $
// $Date: 2017-12-21 15:35:39 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Serial2Client.h>

/*----- PROTECTED REGION END -----*/	//	Serial2Client::Serial2ClientStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Serial2Client_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(Serial2Client::Serial2ClientStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Serial2Client::Serial2ClientStateAllowed.AdditionalMethods

}	//	End of namespace
